language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - cmake
            - libgoogle-glog-dev
            - libatlas-base-dev
            - libeigen3-dev
            - libsuitesparse-dev
            - libgtest-dev
env:
- MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

#branches:
#  only:
#  - master

before_script:
    - wget http://ceres-solver.org/ceres-solver-1.13.0.tar.gz
    - tar zxf ceres-solver-1.13.0.tar.gz
    - cd ceres-solver-1.13.0
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - sudo make install

    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib

    - pip install --user cpp-coveralls

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake .. -DUSE_OPENMP=1 -DCOVERAGE=1
  - make -j2
  - make tests
  - make check

before_install:
  - eval "${MATRIX_EVAL}"

after_success:
  - coveralls --exclude ceres-solver-1.13.0 --exclude docs --exclude samples --exclude tests -E ".*CMakeFiles.*" -E ".*_hmi.cpp" --gcov-options '\-lp' --root ..
